cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    postepoc:
      email: jsmith@gmail.com
      logged_in: false
      name: John Smith
      password: $2b$12$qgpdymNsKCf9Hjwg.NSXiO9/ItCdKVNoJBWQf6EAk9n73HgkAJmEC
      role: admin
preauthorized:
  emails:
  - melsby@gmail.com